apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
     app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - image: docker.io/ryangambinga/udagram-api-feed
        name: backend-feed 
        ports:
            - containerPort: 8080